### ISSUE TITLE
Open Finder windows state is not preserved when toggling between show/hide hidden files

### ISSUE THREAD

**Issue by sasojadrovski** [dimovskidamjan/Boo#1]
Hi @dimovskidamjan,

Thank you for this awesome and handy utility app! Job well done!

I have noticed that once you toggle the hidden files to be visible or hidden, the currently open Finder windows are not preserved, i.e. killing the Finder process does not re-open the windows. Could you please take a look?

Thanks in advance!

**Comment by dimovskidamjan** [comment]
Well noted! Please check the latest commit, the issue should be fixed now.

**Comment by sasojadrovski** [comment]
This was fast! It works great now, thanks!

Keep up the good work!
